name: WebARKitLib test

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: create and enter in the build directory
          run: |
              cd tests && mkdir build && cd build
        - name: Build
          run: cmake ..
        - name: Test
          run: |
              cd bin/Debug && ./webarkit_test.exe