name: WebARKitLib test

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - name: Update Ubuntu and install libjpeg-dev
          run: |
              sudo apt-get update && sudo apt install libjpeg-dev
        - name: Build and test WebARKitLib
          run: |
              cd tests && mkdir build && cd build && cmake -DEMSCRIPTEN_COMP=0 .. && make && ./webarkit_test
        - name: Build WebARKitLib with Emscripten (Docker)
          run: |
             cd ..
             ls
             docker run -dit --name emscripten-webarkit-testing -v $(pwd):/src emscripten/emsdk:3.1.38 bash
             docker exec emscripten-webarkit-testing emcmake cmake -B WebARKitLib/WebARKit/build -S WebARKitLib/WebARKit -DEMSCRIPTEN_COMP=1 ..
             docker exec emscripten-webarkit-testing emmake make -C WebARKitLib/WebARKit/build
              